# Depoy template in account B which will provision role ARole and grant assume role access to account A.
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ARole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: Account A account number
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                sts:ExternalId: 'A-B'
      Path: /
      Policies:
        - PolicyName: A-access-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'